name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Data Source (Reader/Writer)
        - New Forecaster Model
        - New Transformer
        - New Anomaly Detector
        - Workflow Enhancement
        - API Enhancement
        - Documentation
        - Performance Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        I would like to be able to... because...
        Currently, I have to... which is...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would like to use this feature
      render: python
      placeholder: |
        from chronomaly import NewFeature

        # Example of how the feature would be used
        feature = NewFeature(param="value")
        result = feature.do_something()
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I have tried... but it doesn't work because...
        Another option would be... but...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        Links to similar features in other libraries:
        - https://example.com/similar-feature

        Reference papers or documentation:
        - https://example.com/paper
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
